<a href="https://colab.research.google.com/github/NahidurRahaman/Python_Note_Book/blob/main/panda_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
s = pd.Series(np.random.randint(0,7,size=10))
s

0    6
1    6
2    4
3    5
4    2
5    3
6    4
7    6
8    2
9    1
dtype: int64

In [4]:
s.value_counts()

6    3
4    2
2    2
5    1
3    1
1    1
Name: count, dtype: int64

In [6]:
s = pd.Series(["A","B","C","Aaba","Baca",np.nan,"CABA","dog"])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
dtype: object

In [7]:
df=pd.DataFrame(np.random.randn(10,4))
df

          0         1         2         3
0  0.165868 -0.101929 -0.585449 -0.204899
1  0.451172 -0.044879 -1.296168  0.074568
2  0.892545  0.156244 -0.448593 -0.775163
3  0.944194  1.152460 -0.889245 -0.006125
4 -0.515025 -1.228864  0.279242 -0.016215
5  0.020269  1.128152  0.189358  1.796076
6  0.161720  0.487687  0.492954 -0.073269
7 -1.058150 -0.385942  1.358685  0.481649
8 -0.233581 -1.239629  1.749437  0.140916
9 -4.099874  0.091197  1.910879  0.720657